### PR TITLE
fix: monitor objects and delete property

### LINKED ISSUE #217: changed value should be set to true when modifying objects within session
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.26.2

### Plugin version

7.1.0

### Node.js version

18.8.2

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.6.4

### Description

Modifying objects in `session` does not set `changed` to `true`.

### Steps to Reproduce

See `passport-oauth2` - PKCESessionStore (code permalink attached)

https://github.com/jaredhanson/passport-oauth2/blob/be9bf58cee75938c645a9609f0cc87c4c724e7c8/lib/state/pkcesession.js#L48

`req.session[key].state = sstate;`

This line modifies an object within `session`, however `session[key]` is not proxied. Changing this value won't set `changed` to `true`.

### Expected Behavior

`changed` should be set to `true` when modifying an object/array within `session`.

### PR DESCRIPTION
**Pull request by Nanosync**
Fixes #217 

This PR ensures `changed` in Session is set to true by:
- observing modifications to objects (and recursive objects) within Session
- observing when the `delete` keyword is used within Session (and recursive objects)

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -5,6 +5,32 @@ const sodium = require('sodium-native')
 const kObj = Symbol('object')
 const kCookieOptions = Symbol('cookie options')
 
+const proxyCache = new WeakMap()
```
Comment (mcollina) [inline index.js:8]: Why do you need a global WeakMap?

Comment (Nanosync) [reply index.js:8]: It's shared between `sessionProxyHandler` and the function `createProxyHandler` which handles recursive object instances, so that calls to `get` are memoized.

Comment (Nanosync) [reply index.js]: I have separated `WeakMap` into two different scopes as it might have caused confusion. I hope this approach is clearer.

**Comment by mcollina** [comment]
I still don't understand why it needs to be in module scope vs inside the plugin scope.

**Comment by Nanosync** [comment]
@mcollina Do you mean that `sessionProxyCache` should be moved into the scope of `fastifySecureSession`? I was not aware that `fastifySecureSession` would be called multiple times.

File: index.js [hunk 2]
```diff
@@ -304,6 +319,35 @@ class Session {
   }
 }
 
+function createObjectProxyHandler (sessionTarget) {
+  const proxyCache = new WeakMap()
```
Comment (mcollina) [inline index.js:323]: this map should be plugin scoped

File: test/access.js [hunk 3]
```diff
@@ -167,15 +203,68 @@ t.test('session is changed', t => {
     t.same(JSON.parse(response.payload), true)
 
     fastify.inject({
-      method: 'GET',
-      url: '/',
+      method: 'POST',
+      url: '/delete',
```
Comment (mcollina) [inline test/access.js:207]: please do not change this test but add a new one

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
I'm not sure why but the tests are now failing, I'm reverting.

https://github.com/fastify/fastify-secure-session/actions/runs/8631175011/job/23659036483#step:5:117

Feel free to open a fresh PR with this, but these kind of failures are why I generically prefer to avoid Proxy.
